version: '3'
services:
########## ##########
  dev:
    container_name: ge-dev
    image: bilsalak/great-expectations-dev:v-0.1
    volumes:
      - ../project:/home/project
      - ../data:/home/data
    ports:
      - "8888:8888"
    env_file:
      - ./config/server.env